In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.cluster import DBSCAN
# Scikit learn DBSCAN documentation:
# https://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html
import pandas as pd
import numpy as np

In [4]:
#X, y = make_moons(n_samples=1000, noise=0.05)

In [3]:
crime = pd.read_csv('../data/features/crime.csv')
crime

Unnamed: 0  Year  Beat  report_cnt  THEFT  BATTERY  CRIMINAL DAMAGE  \
0              0  2016   111        1843   1143      116             57.0   
1              1  2016   112        1849   1115      123             41.0   
2              2  2016   113        1085    482      151             58.0   
3              3  2016   114        1049    558       93             53.0   
4              4  2016   121         810    349       63             63.0   
...          ...   ...   ...         ...    ...      ...              ...   
1091        1091  2019  2531         690    108      158             71.0   
1092        1092  2019  2532        1026    148      237            104.0   
1093        1093  2019  2533        1604    503      241            137.0   
1094        1094  2019  2534        1192    189      270            149.0   
1095        1095  2019  2535         838    187      151             77.0   

      ASSAULT  DECEPTIVE PRACTICE  OTHER OFFENSE  ...  NON-CRIMINAL_rate  \
0          84               222.0             37  ...                NaN   
1          55               318.0             44  ...           0.000541   
2          46               149.0             21  ...           0.001843   
3          36               132.0             32  ...                NaN   
4          27               118.0             46  ...                NaN   
...       ...                 ...            ...  ...                ...   
1091       62                67.0             58  ...                NaN   
1092       78                82.0             92  ...                NaN   
1093      104               120.0             65  ...                NaN   
1094      118                44.0             72  ...                NaN   
1095       55                39.0             69  ...                NaN   

      HUMAN TRAFFICKING_rate  PUBLIC INDECENCY_rate  \
0                        NaN                    NaN   
1                        NaN                    NaN   
2                        NaN               0.001843   
3                        NaN                    NaN   
4                        NaN                    NaN   
...                      ...                    ...   
1091                     NaN                    NaN   
1092                     NaN                    NaN   
1093                     NaN                    NaN   
1094                     NaN                    NaN   
1095                     NaN                    NaN   

      OTHER NARCOTIC VIOLATION_rate  NON-CRIMINAL (SUBJECT SPECIFIED)_rate  \
0                               NaN                                    NaN   
1                               NaN                                    NaN   
2                               NaN                                    NaN   
3                               NaN                                    NaN   
4                               NaN                                    NaN   
...                             ...                                    ...   
1091                            NaN                                    NaN   
1092                            NaN                                    NaN   
1093                            NaN                                    NaN   
1094                            NaN                                    NaN   
1095                            NaN                                    NaN   

      NON - CRIMINAL_rate  Arrest  Domestic  Arrest_rate  Domestic_rate  
0                     NaN     561      47.0     0.304395       0.025502  
1                     NaN     377      29.0     0.203894       0.015684  
2                     NaN     199      33.0     0.183410       0.030415  
3                     NaN     124      44.0     0.118208       0.041945  
4                     NaN     129      30.0     0.159259       0.037037  
...                   ...     ...       ...          ...            ...  
1091                  NaN     150     140.0     0.21

In [4]:
crime.columns

Index(['Unnamed: 0', 'Year', 'Beat', 'report_cnt', 'THEFT', 'BATTERY',
       'CRIMINAL DAMAGE', 'ASSAULT', 'DECEPTIVE PRACTICE', 'OTHER OFFENSE',
       'NARCOTICS', 'BURGLARY', 'MOTOR VEHICLE THEFT', 'ROBBERY',
       'CRIMINAL TRESPASS', 'WEAPONS VIOLATION', 'OFFENSE INVOLVING CHILDREN',
       'PUBLIC PEACE VIOLATION', 'CRIM SEXUAL ASSAULT',
       'INTERFERENCE WITH PUBLIC OFFICER', 'SEX OFFENSE', 'PROSTITUTION',
       'HOMICIDE', 'ARSON', 'CRIMINAL SEXUAL ASSAULT', 'LIQUOR LAW VIOLATION',
       'STALKING', 'KIDNAPPING', 'GAMBLING', 'INTIMIDATION',
       'CONCEALED CARRY LICENSE VIOLATION', 'OBSCENITY', 'NON-CRIMINAL',
       'HUMAN TRAFFICKING', 'PUBLIC INDECENCY', 'OTHER NARCOTIC VIOLATION',
       'NON-CRIMINAL (SUBJECT SPECIFIED)', 'NON - CRIMINAL', 'THEFT_rate',
       'BATTERY_rate', 'CRIMINAL DAMAGE_rate', 'ASSAULT_rate',
       'DECEPTIVE PRACTICE_rate', 'OTHER OFFENSE_rate', 'NARCOTICS_rate',
       'BURGLARY_rate', 'MOTOR VEHICLE THEFT_rate', 'ROBBERY_rate',
       'C

In [5]:
crime.isna().sum().sort_values().head(20)

Unnamed: 0                 0
BATTERY_rate               0
ASSAULT_rate               0
CRIMINAL TRESPASS          0
OTHER OFFENSE_rate         0
CRIMINAL TRESPASS_rate     0
Arrest                     0
THEFT_rate                 0
OTHER OFFENSE              0
Arrest_rate                0
ASSAULT                    0
BATTERY                    0
THEFT                      0
report_cnt                 0
Beat                       0
Year                       0
CRIMINAL DAMAGE            1
DECEPTIVE PRACTICE_rate    1
CRIMINAL DAMAGE_rate       1
DECEPTIVE PRACTICE         1
dtype: int64

In [18]:
crime_sub = crime[crime['Year'] == 2019].loc[:, ['BATTERY_rate', 'ASSAULT_rate', 'Arrest_rate', 'OTHER OFFENSE_rate', 'report_cnt']]
#subset 2019 data
dbscan = DBSCAN(eps=.03, min_samples=5)
dbscan.fit(crime_sub)

DBSCAN(eps=0.03)

In [19]:
np.unique(dbscan.labels_)

array([-1])

In [20]:
dbscan.core_sample_indices_

array([], dtype=int64)

In [21]:
#dbscan.components_

In [22]:
#same thing but standardize the data first
std_crime_sub = StandardScaler().fit_transform(crime_sub)

In [27]:
std_dbscan = DBSCAN(eps=.9, min_samples=5)
std_dbscan.fit(std_crime_sub)

DBSCAN(eps=0.9)

In [28]:
np.unique(std_dbscan.labels_)

array([-1,  0,  1])

In [29]:
std_dbscan.core_sample_indices_

array([  3,   8,   9,  11,  12,  14,  15,  16,  18,  23,  24,  28,  30,
        31,  35,  36,  37,  38,  39,  40,  43,  45,  46,  55,  56,  61,
        62,  69,  71,  72,  75,  79,  81,  83,  84,  85,  86,  90,  92,
        97, 101, 102, 103, 105, 106, 107, 109, 111, 112, 113, 118, 124,
       125, 128, 135, 136, 143, 145, 148, 152, 153, 155, 156, 157, 159,
       160, 162, 163, 164, 169, 170, 172, 173, 176, 177, 179, 181, 183,
       185, 186, 187, 188, 189, 197, 198, 199, 200, 201, 202, 203, 204,
       208, 212, 217, 221, 224, 227, 229, 230, 231, 232, 236, 238, 242,
       243, 245, 247, 248, 249, 250, 251, 254, 255, 257, 258, 260, 261,
       262, 263, 264, 265, 266, 267, 268, 269, 270, 272])

In [33]:
pd.Series(std_dbscan.labels_).value_counts()

 1    159
-1     97
 0     18
dtype: int64

In [34]:
core_samples_mask = np.zeros_like(std_dbscan.labels_, dtype=bool)
core_samples_mask[std_dbscan.core_sample_indices_] = True
labels = dbscan.labels_

In [92]:
#eval
# Number of clusters in labels, ignoring noise if present.
n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)
n_noise_ = list(labels).count(-1)

print('Estimated number of clusters: %d' % n_clusters_)
print('Estimated number of noise points: %d' % n_noise_)
print("Silhouette Coefficient: %0.3f"
      % metrics.silhouette_score(std_crime_sub, labels))

Estimated number of clusters: 10
Estimated number of noise points: 1045
Silhouette Coefficient: -0.309


In [91]:
len(X)

1000